version: "3.9"

services:
  http:
    image: nginx:alpine
    container_name: http
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tp3-net
    depends_on:
      - script

  script:
    build: ./php
    container_name: script
    volumes:
      - ./src:/app
    networks:
      - tp3-net
    depends_on:
      - data

  data:
    image: mariadb
    container_name: data
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: tp3
      MARIADB_USER: tp3
      MARIADB_PASSWORD: tp3
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - tp3-net

networks:
  tp3-net:
